# Generated by Django 3.0.8 on 2022-05-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sabiman.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=9)),
                ('role', models.CharField(choices=[('normal', 'normal'), ('class rep', 'class rep'), ('course adviser', 'course adviser'), ('HOD', 'HOD')], default='normal', max_length=16)),
                ('phone_number_1', models.CharField(max_length=11, null=True, unique=True)),
                ('phone_number_2', models.CharField(max_length=11, null=True, unique=True)),
                ('is_a_student', models.BooleanField(default=False)),
                ('is_a_lecturer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', sabiman.manager.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('faculty_code', models.CharField(max_length=5, unique=True)),
                ('email_code', models.CharField(max_length=250, unique=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mat_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('own_number', models.CharField(max_length=11, unique=True)),
                ('own_number_2', models.CharField(max_length=11, unique=True)),
                ('student_level', models.CharField(choices=[('100 Level', '100'), ('200 Level', '200'), ('300 Level', '300'), ('400 Level', '400')], default=100, max_length=50)),
                ('relative1_name', models.CharField(max_length=255)),
                ('relative1_phone', models.CharField(max_length=11, unique=True)),
                ('relative2_name', models.CharField(max_length=255)),
                ('relative2_phone', models.CharField(max_length=11, unique=True)),
                ('relative3_name', models.CharField(max_length=255)),
                ('relative3_phone', models.CharField(max_length=11, unique=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('student_acct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=9, null=True)),
                ('mat_no', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(choices=[('100 Level', '100'), ('200 Level', '200'), ('300 Level', '300'), ('400 Level', '400')], default='100', max_length=50)),
                ('role', models.CharField(choices=[('normal', 'normal'), ('class rep', 'class rep'), ('course adviser', 'course adviser'), ('HOD', 'HOD')], default='normal', max_length=16)),
                ('relative1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative1_phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('relative2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative2_phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('relative3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative3_phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='sabiman.Department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sabiman.Faculty')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_you_teach', multiselectfield.db.fields.MultiSelectField(choices=[('100 Level', '100'), ('200 Level', '200'), ('300 Level', '300'), ('400 Level', '400')], default=100, max_length=39)),
                ('phone_number_1', models.CharField(max_length=11, null=True, unique=True)),
                ('phone_number_2', models.CharField(max_length=11, null=True, unique=True)),
                ('is_lecturer', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('lecturer_acct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_faculty', to='sabiman.Faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sabiman.Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sabiman.Faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
