# Generated by Django 3.0.8 on 2022-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabiman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='role',
            field=models.CharField(choices=[('normal', 'normal'), ('course adviser', 'course adviser'), ('HOD', 'HOD')], default='normal', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('normal', 'normal'), ('class rep', 'class rep')], default='normal', max_length=16, null=True),
        ),
    ]
